### ISSUE TITLE
INDRA and ERG cannot generate locative sentences with "here" and "there"

### ISSUE THREAD

**Issue by davidmoeljadi** [goodmami/demophin#13]
I tried in ERG:
I am here
I am there
I am at home

ERG can generate "I am at home" but not "I am here" and "I am there".

I tried in INDRA:
Saya ada di sini "I am here"
Saya ada di sana "I am there"
Saya ada di rumah "I am at home"

INDRA cannot generate all those sentences.

**Comment by goodmami** [comment]
Thanks for the report.

I see what you mean. Those sentences can be generated with the ERG and ACE (e.g. at the command line), but something is failing when Demophin tries to generate them. I haven't yet figured out the problem.

**Comment by goodmami** [comment]
Hmm, today when I try I cannot generate those sentences with either the ERG 1212, ERG 1214, or the latest INDRA. This leads me to believe that the failure to generate is a problem with the grammars and not Demophin. Nevertheless, Demophin is failing to provide a useful error message. Issue #4 will fix that part.

I'm closing this as invalid for now. Let me know if you have a sentence that parses and generates with ACE at the commandline, but does not generate with Demophin, and I'll reopen it.
